Mspt 1899 set leg id by ribbon
bbc/lsp-legid-setter pull request #1
Opened 2022-05-26 06:52 UTC by xuq01

2022-05-26 11:20 UTC, GeorgeBowers commented on component-test/cucumber/features/lsp-legid-setter.feature
> +  Scenario: get channel endpoint from state api but it returns error
bit nitpicky but I think theres some inconsistent capitalisations of words in the component test steps..

Scenario: get - is lowercase G

And Ribbon Get leg - uppercase

medialive state api should be capitalized too because its a noun.

2022-05-26 11:21 UTC, GeorgeBowers commented on component-test/cucumber/features/support/00_env.rb
> +      'ENVIRONMENT' => 'Dev',
again extremely nitpicky but usually we have the cucumber test environment as just "cucumber"

2022-05-26 11:23 UTC, GeorgeBowers requested changes
Just some small extremely petty nitpicks, otherwise LGTM

2022-05-26 12:43 UTC, xuq01 commented on component-test/cucumber/features/lsp-legid-setter.feature
> +  Scenario: get channel endpoint from state api but it returns error
fix in new commit

2022-05-26 12:43 UTC, xuq01 commented on component-test/cucumber/features/support/00_env.rb
> +      'ENVIRONMENT' => 'Dev',
fix in new commit

2022-05-27 08:56 UTC, GeorgeBowers approved these changes

2022-05-27 11:13 UTC, merged